# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "DAY_TOUR" ("DATE" DATE NOT NULL,"DAYTOUR_ID" OTHER NOT NULL PRIMARY KEY,"TITLE" VARCHAR NOT NULL,"DESCRIPTION" VARCHAR(20000) NOT NULL,"WEATHER_COND" VARCHAR NOT NULL,"ROAD_COND" VARCHAR NOT NULL,"CATEGORY" VARCHAR NOT NULL);
create unique index "INDEX_DATE" on "DAY_TOUR" ("DATE");
create table "IMAGES" ("ID" OTHER NOT NULL PRIMARY KEY,"NAME" VARCHAR NOT NULL,"DATETIME" TIMESTAMP NOT NULL,"DATETIME_ZONE" VARCHAR NOT NULL,"PATH" VARCHAR NOT NULL);
create table "TRACK" ("TRACK_ID" OTHER NOT NULL PRIMARY KEY,"TRACK_NAME" VARCHAR,"TRACK_ACTIVITY_TYPE" VARCHAR NOT NULL);
create table "TRACK_METADATA" ("TRACK_ID" OTHER NOT NULL PRIMARY KEY,"DESCRIPTION" VARCHAR(20000),"DISTANCE" REAL,"TIMERTIME" REAL,"TOTALELAPSEDTIME" REAL,"MOVINGTIME" REAL,"STOPPEDTIME" REAL,"MOVINGSPEED" REAL,"MAXSPEED" REAL,"MAXELEVATION" REAL,"MINELEVATION" REAL,"ASCENT" REAL,"DESCENT" REAL,"AVGASCENTRATE" REAL,"MAXASCENTRATE" REAL,"AVGDESCENTRATE" REAL,"MAXDESCENTRATE" REAL,"CALORIES" REAL,"AVGHEARTREATE" REAL);
create table "TRACK_POINTS" ("TRACK_ID" OTHER NOT NULL,"LATITUDE" REAL NOT NULL,"LONGITUDE" REAL NOT NULL,"ELEVATION" REAL NOT NULL,"DATE" TIMESTAMP NOT NULL PRIMARY KEY,"TIME_ZONE" VARCHAR NOT NULL,"SHOW_IN_OVERVIEW" BOOLEAN NOT NULL);
create unique index "TRACK_POINT_IDX" on "TRACK_POINTS" ("DATE");
create table "TRACK_TO_LOCALDATE" ("TRACK_ID" OTHER NOT NULL,"LOCAL_DATE" DATE NOT NULL);
create table "TRIP" ("TITLE" VARCHAR NOT NULL,"DESC" VARCHAR(20000) DEFAULT 'No Description' NOT NULL,"SHORT_NAME" VARCHAR NOT NULL PRIMARY KEY,"START_DATE" DATE NOT NULL,"END_DATE" DATE NOT NULL);
create table "USER" ("UNAME" VARCHAR NOT NULL PRIMARY KEY,"PASSWORD" VARCHAR NOT NULL,"DNAME" VARCHAR NOT NULL);
alter table "TRACK_METADATA" add constraint "TRACK_FK" foreign key("TRACK_ID") references "TRACK"("TRACK_ID") on update NO ACTION on delete NO ACTION;
alter table "TRACK_POINTS" add constraint "TRACK_POINT_FK" foreign key("TRACK_ID") references "TRACK"("TRACK_ID") on update NO ACTION on delete NO ACTION;
alter table "TRACK_TO_LOCALDATE" add constraint "TRACK_TO_LOCAL_DATE_FK" foreign key("TRACK_ID") references "TRACK"("TRACK_ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "TRACK_TO_LOCALDATE" drop constraint "TRACK_TO_LOCAL_DATE_FK";
alter table "TRACK_POINTS" drop constraint "TRACK_POINT_FK";
alter table "TRACK_METADATA" drop constraint "TRACK_FK";
drop table "USER";
drop table "TRIP";
drop table "TRACK_TO_LOCALDATE";
drop table "TRACK_POINTS";
drop table "TRACK_METADATA";
drop table "TRACK";
drop table "IMAGES";
drop table "DAY_TOUR";

