# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "DAY_TOUR" ("DATE" DATE NOT NULL,"DAYTOUR_ID" UUID NOT NULL PRIMARY KEY,"TITLE" VARCHAR(254) NOT NULL,"DESCRIPTION" VARCHAR(20000) NOT NULL,"WEATHER_COND" VARCHAR(254) NOT NULL,"ROAD_COND" VARCHAR(254) NOT NULL,"CATEGORY" VARCHAR(254) NOT NULL);
create unique index "INDEX_DATE" on "DAY_TOUR" ("DATE");
create table "IMAGES" ("ID" UUID NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) NOT NULL,"DATETIME" TIMESTAMP NOT NULL,"DATETIME_ZONE" VARCHAR(254) NOT NULL,"PATH" VARCHAR(254) NOT NULL);
create table "TRACK" ("TRACK_ID" UUID NOT NULL PRIMARY KEY,"TRACK_NAME" VARCHAR(254),"TRACK_ACTIVITY_TYPE" VARCHAR(254) NOT NULL);
create table "TRACK_METADATA" ("TRACK_ID" UUID NOT NULL PRIMARY KEY,"DESCRIPTION" VARCHAR(20000),"DISTANCE" FLOAT,"TIMERTIME" FLOAT,"TOTALELAPSEDTIME" FLOAT,"MOVINGTIME" FLOAT,"STOPPEDTIME" FLOAT,"MOVINGSPEED" FLOAT,"MAXSPEED" FLOAT,"MAXELEVATION" FLOAT,"MINELEVATION" FLOAT,"ASCENT" FLOAT,"DESCENT" FLOAT,"AVGASCENTRATE" FLOAT,"MAXASCENTRATE" FLOAT,"AVGDESCENTRATE" FLOAT,"MAXDESCENTRATE" FLOAT,"CALORIES" FLOAT,"AVGHEARTREATE" FLOAT);
create table "TRACK_POINTS" ("TRACK_ID" UUID NOT NULL,"LATITUDE" FLOAT NOT NULL,"LONGITUDE" FLOAT NOT NULL,"ELEVATION" FLOAT NOT NULL,"DATE" TIMESTAMP NOT NULL PRIMARY KEY,"TIME_ZONE" VARCHAR(254) NOT NULL,"SHOW_IN_OVERVIEW" BOOLEAN NOT NULL);
create unique index "TRACK_POINT_IDX" on "TRACK_POINTS" ("DATE");
create table "TRACK_TO_LOCALDATE" ("TRACK_ID" UUID NOT NULL,"LOCAL_DATE" DATE NOT NULL);
create table "TRIP" ("TITLE" VARCHAR(254) NOT NULL,"DESC" VARCHAR(20000) DEFAULT 'No Description' NOT NULL,"SHORT_NAME" VARCHAR(254) NOT NULL PRIMARY KEY,"START_DATE" DATE NOT NULL,"END_DATE" DATE NOT NULL);
create table "USER" ("UNAME" VARCHAR(254) NOT NULL PRIMARY KEY,"PASSWORD" VARCHAR(254) NOT NULL,"DNAME" VARCHAR(254) NOT NULL);
alter table "TRACK_METADATA" add constraint "TRACK_FK" foreign key("TRACK_ID") references "TRACK"("TRACK_ID") on update NO ACTION on delete NO ACTION;
alter table "TRACK_POINTS" add constraint "TRACK_POINT_FK" foreign key("TRACK_ID") references "TRACK"("TRACK_ID") on update NO ACTION on delete NO ACTION;
alter table "TRACK_TO_LOCALDATE" add constraint "TRACK_TO_LOCAL_DATE_FK" foreign key("TRACK_ID") references "TRACK"("TRACK_ID") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "TRACK_METADATA" drop constraint "TRACK_FK";
alter table "TRACK_POINTS" drop constraint "TRACK_POINT_FK";
alter table "TRACK_TO_LOCALDATE" drop constraint "TRACK_TO_LOCAL_DATE_FK";
drop table "DAY_TOUR";
drop table "IMAGES";
drop table "TRACK";
drop table "TRACK_METADATA";
drop table "TRACK_POINTS";
drop table "TRACK_TO_LOCALDATE";
drop table "TRIP";
drop table "USER";

